from wish_flask.exceptions.errors import Errors as FlaskErrors

class Error(FlaskErrors):
    DUPLICATE_REPORT_NAME = 1001
    DUPLICATE_REPORT_VERSION = 1002
    INVALID_GOOGLE_URL = 1003
    REPORT_NOT_FOUND = 1004
    TEMPLATE_NOT_FOUND = 1005
    VERSION_NOT_FOUND = 1006
    VERSION_ARCHIVED = 1007
    VERSION_ACTIVATED = 1008